apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: loki-datasource
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  valuesFrom:
    - targetPath: 'secureJsonData.httpHeaderValue1'
      valueFrom:
        secretKeyRef:
          name: 'grafana-serviceaccount-token'
          key: 'token'
  instanceSelector:
    matchLabels:
      dashboards: 'grafana-paas'
  datasource:
    name: loki
    type: loki
    access: proxy
    basicAuth: true
    url: 'https://logging-loki-gateway-http.openshift-logging.svc.cluster.local:8080/api/logs/v1/application/'
    jsonData:
      tlsSkipVerify: true
      timeInterval: '5s'
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Bearer ${token}'
    editable: true