apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus-datasource
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  valuesFrom:
    - targetPath: 'secureJsonData.httpHeaderValue1'
      valueFrom:
        secretKeyRef:
          name: 'grafana-serviceaccount-token'
          key: 'token'
  instanceSelector:
    matchLabels:
      dashboards: 'grafana-paas'
  datasource:
    name: prometheus
    type: prometheus
    access: proxy
    basicAuth: true
    url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
    isDefault: true
    jsonData:
      tlsSkipVerify: true
      timeInterval: '5s'
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'Bearer ${token}'
    editable: true