apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
    kubernetes.io/service-account.name: "grafana-paas-sa" 
  name: grafana-serviceaccount-token
type: kubernetes.io/service-account-token 
