{{- if eq .Values.argocd_paasns_gen.enabled "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paasns-edit-rolebinding
subjects:
  - kind: ServiceAccount
    name: argo-service-argocd-server
roleRef:
  kind: Role
  name: paasns-edit
  apiGroup: rbac.authorization.k8s.io
{{ end }}