apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-argocd-application-controller
  namespace: {{ .Values.paas }}-{{ .Values.capability }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: argocd-application-controller
        maxAllowed:
          cpu: '4'
          memory: 10Gi
        minAllowed:
          cpu: 20m
          memory: 50Mi
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: argo-service-application-controller
  updatePolicy:
    updateMode: Initial