apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-argocd-applicationset-controller
  namespace: {{ .Values.paas }}-{{ .Values.capability }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: argocd-applicationset-controller
        maxAllowed:
          cpu: '500m'
          memory: 1Gi
        minAllowed:
          cpu: 20m
          memory: 50Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: argo-service-applicationset-controller
  updatePolicy:
    updateMode: Initial