apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-argocd-repo-server
  namespace: {{ .Values.paas }}-{{ .Values.capability }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: argocd-repo-server
        maxAllowed:
          cpu: '1'
          memory: 1Gi
        minAllowed:
          cpu: 20m
          memory: 50Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: argo-service-repo-server
  updatePolicy:
    updateMode: Initial