{{- if eq .Values.argocd_paasns_gen.enabled "true" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: vpa-argocd-paasns-gen
  namespace: {{ .Values.paas }}-{{ .Values.capability }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: argocd-paasns-gen-service
        maxAllowed:
          cpu: 150m
          memory: 512Mi
        minAllowed:
          cpu: 20m
          memory: 50Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: argocd-paasns-gen
  updatePolicy:
    updateMode: Initial
  {{ end }}